spring.application.name=authrex

# API-Only Security Configuration (Flat Structure)

spring.web.resources.add-mappings=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.filter.order=0
spring.main.allow-circular-references=true

# Disable all web UI features
thymeleaf.cache=true
mvc.servlet.load-on-startup=1
resources.static-locations=classpath:/


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true
management.health.diskspace.enabled=true

# JWT Configuration

app.jwt.secret=${JWT_SECRET:your-256-bit-secret-here}
app.jwt.expiration=${JWT_EXPIRATION:3600}
app.jwt.issuer=${JWT_ISSUER:authrex-service}
app.app.jwt.audience=${JWT_AUDIENCE:internal-apis}

app.jwt.private-key=classpath:jwt_certs/jwtRS256.key
app.jwt.public-key=classpath:jwt_certs/jwtRS256.key.pub


# Security Headers (Applied via filter)
security.headers=
hsts=none
xss=block
frame-options=deny
content-security-policy=default-src 'none'; script-src 'none'; style-src 'none'


max.days.allowed.password.lifetime=90
app.password.history-size=3
jwt.refresh.expiration=7

spring.scheduler.cron.expired-token-cleanup=0 0 2 * * ?

write.datasource.url=jdbc:postgresql://localhost:5432/authrex
write.datasource.username=postgres
write.datasource.password=ofspain86

write.datasource.hikari.maximum-pool-size=5
write.datasource.hikari.connection-timeout=30000
write.datasource.hikari.idle-timeout=300000
write.datasource.hikari.max-lifetime=1800000
write.datasource.hikari.leak-detection-threshold=30000


# Sort operations and tags alphabetically
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#debug=true

application.env=dev

# Common Redis settings
spring.redis.timeout=5000

# Default mode (override in profile-specific files)
spring.redis.cluster-enabled=false

# Default pool settings
spring.redis.lettuce.refresh-period=60
spring.redis.lettuce.pool.max-idle=50
spring.redis.lettuce.pool.min-idle=5
spring.redis.lettuce.pool.max-active=50
spring.redis.lettuce.pool.max-wait=-1
spring.redis.lettuce.pool.time-between-eviction-runs-millis=300000

spring.profiles.active=dev



