# Local Docker Redis or developer machine
spring.redis.cluster-enabled=false
spring.redis.standalone.host=localhost
spring.redis.standalone.port=6379

# Faster pool/refresh for dev
spring.redis.timeout=2000
spring.redis.lettuce.refresh-period=30
spring.redis.lettuce.pool.max-idle=10
spring.redis.lettuce.pool.min-idle=1
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=500
spring.redis.lettuce.pool.time-between-eviction-runs-millis=60000
